name: CD - Docs - prod

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'docs-v*' # Push events to every tag not containing / and starting with 'docs-v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.DOCS_DEPLOY_HOOK }}
