name: CD - Web - prod

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'web-v*' # Push events to every tag not containing / and starting with 'web-v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.WEB_DEPLOY_HOOK }}
